Update embassy commit rev for neopixel example
Currently, the following build error is generated when running cargo
build in examples/nrf52/adafruit-nrf-feather/neopixel:

Building /drogue-device/examples/nrf52/adafruit-nrf-feather/neopixel
$ cargo build --release
    Updating git repository `https://github.com/embassy-rs/embassy.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `embassy`

Caused by:
  Unable to update https://github.com/embassy-rs/embassy.git?rev=6a3b3ca755073f73b24fad89a109fba7132d1312#6a3b3ca7

Caused by:
  object not found - no match for id (6a3b3ca755073f73b24fad89a109fba7132d1312); class=Odb (9); code=NotFound (-3)
Error: command `cargo build --release` failed, exit status: 101

I've not looked into why this commit is no longer available, but
updating it to the same revision that other examples uses, allowed the
example to build (and also allowed 'xtask ci' to complete successfully).